### ISSUE TITLE
Related records on the list throw errors

### ISSUE THREAD

**Issue by joeewing** [mshanemc/AnythingPath#2]
Get an error when attempting to click on a record in the Board view.

Uncaught Action failed: one$centerStage$controller$handleDelegatedEvent [TypeError: Cannot read property 'substring' of undefined]
throws at https://emn--jam.lightning.force.com/auraFW/javascript/qnVOSqP_GYth6AWC2fT1jQ/aura_prod.js:1:27
    at Object.handler_force_navigateToSObject (https://emn--jam.lightning.force.com/l/%7B%22mode%22%3A%22PROD%22%2C%22app%22%3A%22one%3Aone%22%2C%22fwuid%22%3A%22qnVOSqP_GYth6AWC2fT1jQ%22%2C%22loaded%22%3A%7B%22APPLICATION%40markup%3A%2F%2Fone%3Aone%22%3A%221qGw-iSWHC0W_5PrUI8h1g%22%7D%2C%22requestedLocales%22%3A%5B%22en_US%22%2C%22en%22%5D%2C%22ls%22%3A%22YN%22%7D/app.js:5112:182)
    at https://emn--jam.lightning.force.com/l/%7B%22mode%22%3A%22PROD%22%2C%22app%22%3A%22one%3Aone%22%2C%22fwuid%22%3A%22qnVOSqP_GYth6AWC2fT1jQ%22%2C%22loaded%22%3A%7B%22APPLICATION%40markup%3A%2F%2Fone%3Aone%22%3A%221qGw-iSWHC0W_5PrUI8h1g%22%7D%2C%22requestedLocales%22%3A%5B%22en_US%22%2C%22en%22%5D%2C%22ls%22%3A%22YN%22%7D/app.js:3524:244
    at Object._handleNavigationEvent (https://emn--jam.lightning.force.com/l/%7B%22mode%22%3A%22PROD%22%2C%22app%22%3A%22one%3Aone%22%2C%22fwuid%22%3A%22qnVOSqP_GYth6AWC2fT1jQ%22%2C%22loaded%22%3A%7B%22APPLICATION%40markup%3A%2F%2Fone%3Aone%22%3A%221qGw-iSWHC0W_5PrUI8h1g%22%7D%2C%22requestedLocales%22%3A%5B%22en_US%22%2C%22en%22%5D%2C%22ls%22%3A%22YN%22%7D/app.js:3524:418)
    at Object.handleEvent (https://emn--jam.lightning.force.com/l/%7B%22mode%22%3A%22PROD%22%2C%22app%22%3A%22one%3Aone%22%2C%22fwuid%22%3A%22qnVOSqP_GYth6AWC2fT1jQ%22%2C%22loaded%22%3A%7B%22APPLICATION%40markup%3A%2F%2Fone%3Aone%22%3A%221qGw-iSWHC0W_5PrUI8h1g%22%7D%2C%22requestedLocales%22%3A%5B%22en_US%22%2C%22en%22%5D%2C%22ls%22%3A%22YN%22%7D/app.js:3523:312)
    at handleDelegatedEvent (https://emn--jam.lightning.force.com/l/%7B%22mode%22%3A%22PROD%22%2C%22app%22%3A%22one%3Aone%22%2C%22fwuid%22%3A%22qnVOSqP_GYth6AWC2fT1jQ%22%2C%22loaded%22%3A%7B%22APPLICATION%40markup%3A%2F%2Fone%3Aone%22%3A%221qGw-iSWHC0W_5PrUI8h1g%22%7D%2C%22requestedLocales%22%3A%5B%22en_US%22%2C%22en%22%5D%2C%22ls%22%3A%22YN%22%7D/app.js:3521:72)
    at G.qc (https://emn--jam.lightning.force.com/auraFW/javascript/qnVOSqP_GYth6AWC2fT1jQ/aura_prod.js:275:170)
    at https://emn--jam.lightning.force.com/auraFW/javascript/qnVOSqP_GYth6AWC2fT1jQ/aura_prod.js:229:72
    at https://emn--jam.lightning.force.com/auraFW/javascript/qnVOSqP_GYth6AWC2fT1jQ/aura_prod.js:265:424
    at $.z.ab (https://emn--jam.lightning.force.com/auraFW/javascript/qnVOSqP_GYth6AWC2fT1jQ/aura_prod.js:522:141)
    at O.M (https://emn--jam.lightning.force.com/auraFW/javascript/qnVOSqP_GYth6AWC2fT1jQ/aura_prod.js:264:81)

**Comment by mshanemc** [comment]
I'm not using a substring function anywhere in the code (that I know of!)

Can you try turning off LockerService (in critical updates) and let me know if it changes the behavior?

**Comment by joeewing** [comment]
Looks like in the summer 16 release of Salesforce, there was a security enhancement called lockerservice. For orgs that previously had no custom components, this feature is automatically enabled with no option to disable.  This is done to ensure that all new development around components follows the new security architecture.  Unfortunately, AnythingBoard, being a demo component, does not adhere the new lockerservice architecture.
