### ISSUE TITLE
Please help - Error when drilling down

### ISSUE THREAD

**Issue by heydeepak** [mshanemc/AnythingPath#3]
Uncaught Action failed: forceSearch$entitySelector$controller$init [TypeError: Cannot read property 'Account__r' of null]
throws at https://warehouse--hserdev.lightning.force.com/auraFW/javascript/S8McHzEoUFAXrY8BUJ5Khw/aura_proddebug.js:14724:9
    at AttributeSet.set (https://warehouse--hserdev.lightning.force.com/auraFW/javascript/S8McHzEoUFAXrY8BUJ5Khw/aura_proddebug.js:7635:30)
    at componentConstructor.Component.set (https://warehouse--hserdev.lightning.force.com/auraFW/javascript/S8McHzEoUFAXrY8BUJ5Khw/aura_proddebug.js:4675:35)
    at PropertyReferenceValue.set (https://warehouse--hserdev.lightning.force.com/auraFW/javascript/S8McHzEoUFAXrY8BUJ5Khw/aura_proddebug.js:3169:37)
    at AttributeSet.set (https://warehouse--hserdev.lightning.force.com/auraFW/javascript/S8McHzEoUFAXrY8BUJ5Khw/aura_proddebug.js:7655:17)
    at componentConstructor.Component.set (https://warehouse--hserdev.lightning.force.com/auraFW/javascript/S8McHzEoUFAXrY8BUJ5Khw/aura_proddebug.js:4675:35)
    at PropertyReferenceValue.set (https://warehouse--hserdev.lightning.force.com/auraFW/javascript/S8McHzEoUFAXrY8BUJ5Khw/aura_proddebug.js:3169:37)
    at AttributeSet.set (https://warehouse--hserdev.lightning.force.com/auraFW/javascript/S8McHzEoUFAXrY8BUJ5Khw/aura_proddebug.js:7655:17)
    at componentConstructor.Component.set (https://warehouse--hserdev.lightning.force.com/auraFW/javascript/S8McHzEoUFAXrY8BUJ5Khw/aura_proddebug.js:4675:35)
    at Object.setCurrentEntity (https://warehouse--hserdev.lightning.force.com/l/%7B%22mode%22%3A%22PRODDEBUG%22%2C%22app%22%3A%22one%3Aone%22%2C%22fwuid%22%3A%22S8McHzEoUFAXrY8BUJ5Khw%22%2C%22loaded%22%3A%7B%22APPLICATION%40markup%3A%2F%2Fone%3Aone%22%3A%22wVbsvUcty_25xpcVFAmREw%22%7D%2C%22requestedLocales%22%3A%5B%22en_US%22%2C%22en%22%5D%2C%22ls%22%3A%22YN%22%7D/app.js:31888:13)
    at Object.init (https://warehouse--hserdev.lightning.force.com/l/%7B%22mode%22%3A%22PRODDEBUG%22%2C%22app%22%3A%22one%3Aone%22%2C%22fwuid%22%3A%22S8McHzEoUFAXrY8BUJ5Khw%22%2C%22loaded%22%3A%7B%22APPLICATION%40markup%3A%2F%2Fone%3Aone%22%3A%22wVbsvUcty_25xpcVFAmREw%22%7D%2C%22requestedLocales%22%3A%5B%22en_US%22%2C%22en%22%5D%2C%22ls%22%3A%22YN%22%7D/app.js:31849:34)

**Comment by mshanemc** [comment]
AnythingPath or AnythingBoard?

If it's board, try turning off the locker service critical update.

**Comment by joeewing** [comment]
Looks like in the summer 16 release of Salesforce, there was a security enhancement called lockerservice. For orgs that previously had no custom components, this feature is automatically enabled with no option to disable. This is done to ensure that all new development around components follows the new security architecture. Unfortunately, AnythingBoard, being a demo component, does not adhere the new lockerservice architecture.

**Comment by heydeepak** [comment]
Thanks for the pointers. Installing package on my dev org (that previously had custom components) seem to have resolved the sandbox error as well.
